/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PuzzleEncodedPuzzleStringRouteImport } from './routes/puzzle.$encodedPuzzleString'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzleEncodedPuzzleStringRoute =
  PuzzleEncodedPuzzleStringRouteImport.update({
    id: '/puzzle/$encodedPuzzleString',
    path: '/puzzle/$encodedPuzzleString',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/puzzle/$encodedPuzzleString': typeof PuzzleEncodedPuzzleStringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/puzzle/$encodedPuzzleString': typeof PuzzleEncodedPuzzleStringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/puzzle/$encodedPuzzleString': typeof PuzzleEncodedPuzzleStringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/puzzle/$encodedPuzzleString'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/puzzle/$encodedPuzzleString'
  id: '__root__' | '/' | '/puzzle/$encodedPuzzleString'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PuzzleEncodedPuzzleStringRoute: typeof PuzzleEncodedPuzzleStringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzle/$encodedPuzzleString': {
      id: '/puzzle/$encodedPuzzleString'
      path: '/puzzle/$encodedPuzzleString'
      fullPath: '/puzzle/$encodedPuzzleString'
      preLoaderRoute: typeof PuzzleEncodedPuzzleStringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PuzzleEncodedPuzzleStringRoute: PuzzleEncodedPuzzleStringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
